services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Allocate memory to Elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data # Persist data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - logging_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cat/health?h=st | grep -q 'green\\|yellow'"]
      interval: 20s
      timeout: 15s
      retries: 10
      start_period: 30s

  vector:
    image: timberio/vector:latest-alpine
    volumes:
      - ./vector/vector.toml:/etc/vector/vector.toml:ro
      - ./input.log:/input.log:ro
      - ./outputs:/outputs
    ports:
      - "8686:8686"
    command: ["--config", "/etc/vector/vector.toml"]
    environment:
      VECTOR_ES_HOST: http://elasticsearch:9200
    networks:
      - logging_network
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 # Connect to Elasticsearch service name
    ports:
      - "5601:5601"
    networks:
      - logging_network
    depends_on:
      elasticsearch:
        condition: service_healthy

  pytest-runner:
    build:
      context: .
      dockerfile: Dockerfile.pytest
    container_name: pytest-runner
    volumes:
      - ./tests:/app/tests:ro
      - ./tests/test_results:/app/test_results
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - logging_network
    depends_on:
      vector:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    command: >
      sh -c "echo 'Waiting for logs to be indexed...' && sleep 15 &&
      pytest -W \"ignore:Module already imported:pytest.PytestWarning\"
      -W \"always::pytest.PytestWarning\"
      --html=/app/test_results/report.html --self-contained-html
      /app/tests/test_logs.py"

volumes:
  esdata: # Define the volume for Elasticsearch data persistence

networks:
  logging_network:
    driver: bridge
